# Generated by Django 5.0.6 on 2024-06-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_topic_options_post_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='consulta',
            new_name='pregunta',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='telefono',
        ),
    ]
