# Generated by Django 5.0.6 on 2024-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mensaje_visto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='posts', to='api.topic', verbose_name='temas'),
        ),
    ]
